import type {
  ClientRecord,
  DashboardAlert,
  DashboardMetric,
  Equipment,
  PlannerEvent,
  Technician,
  TechnicianAgendaItem,
  WorkOrderDetail,
  WorkOrderSummary,
  WorkReport,
} from "@/lib/data/contracts";

export const technicians: Technician[] = [
  { id: "tecnico1", code: "tecnico1", name: "Cristian Hernan Madera", color: "#2563eb", active: true },
  { id: "tecnico2", code: "tecnico2", name: "Daniel Esteban Moreno", color: "#16a34a", active: true },
  { id: "tecnico3", code: "tecnico3", name: "Pedro Casacuberta", color: "#ea580c", active: true },
  { id: "tecnico4", code: "tecnico4", name: "Miquel Puchol", color: "#9333ea", active: true },
  { id: "tecnico5", code: "tecnico5", name: "Carlos Gracia", color: "#db2777", active: true },
  { id: "tecnico6", code: "tecnico6", name: "Alfredo Ferreyra", color: "#0891b2", active: true },
  { id: "tecnico7", code: "tecnico7", name: "Abel Jimenez", color: "#65a30d", active: true },
  { id: "tecnico8", code: "tecnico8", name: "Marco Chillon", color: "#dc2626", active: true },
];

export const clients: ClientRecord[] = [
  {
    id: "cliente1",
    name: "Cliente Industrial 1",
    taxId: "B10000001",
    city: "Madrid",
    address: "Calle Tecnica 101",
    contactName: "Responsable 1",
    contactPhone: "600000001",
    equipmentCount: 3,
    openOrders: 2,
  },
  {
    id: "cliente2",
    name: "Cliente Industrial 2",
    taxId: "B10000002",
    city: "Valencia",
    address: "Avenida Servicio 22",
    contactName: "Responsable 2",
    contactPhone: "600000002",
    equipmentCount: 2,
    openOrders: 1,
  },
  {
    id: "cliente3",
    name: "Cliente Industrial 3",
    taxId: "B10000003",
    city: "Barcelona",
    address: "Poligono Norte 8",
    contactName: "Responsable 3",
    contactPhone: "600000003",
    equipmentCount: 4,
    openOrders: 3,
  },
];

export const equipment: Equipment[] = [
  {
    id: "equipo1",
    clientId: "cliente1",
    name: "Compresor principal",
    category: "compressor",
    serialNumber: "SER-0001",
    manufacturer: "Fabricante A",
    model: "Modelo A1",
    location: "Sala de compresores",
    status: "active",
  },
  {
    id: "equipo2",
    clientId: "cliente1",
    name: "Secador linea 1",
    category: "dryer",
    serialNumber: "SER-0002",
    manufacturer: "Fabricante B",
    model: "Modelo D2",
    location: "Linea 1",
    status: "active",
  },
  {
    id: "equipo3",
    clientId: "cliente2",
    name: "Deposito vertical",
    category: "tank",
    serialNumber: "SER-0003",
    manufacturer: "Fabricante C",
    model: "Modelo T1",
    location: "Patio tecnico",
    status: "attention",
  },
  {
    id: "equipo4",
    clientId: "cliente3",
    name: "Filtro principal",
    category: "filter",
    serialNumber: "SER-0004",
    manufacturer: "Fabricante D",
    model: "Modelo F9",
    location: "Cabecera red",
    status: "active",
  },
  {
    id: "equipo5",
    clientId: "cliente3",
    name: "Compresor respaldo",
    category: "compressor",
    serialNumber: "SER-0005",
    manufacturer: "Fabricante A",
    model: "Modelo A2",
    location: "Sala secundaria",
    status: "stopped",
  },
];

export const workOrders: WorkOrderSummary[] = [
  {
    id: "ot1",
    number: "OT-0001",
    title: "Mantenimiento preventivo trimestral",
    type: "maintenance",
    priority: "normal",
    status: "planned",
    billingStatus: "not_ready",
    clientId: "cliente1",
    clientName: "Cliente Industrial 1",
    equipmentId: "equipo1",
    equipmentLabel: "Compresor principal",
    assignedTechnicianIds: ["tecnico1"],
    plannedStart: "2026-04-01T08:00:00.000Z",
    plannedEnd: "2026-04-01T10:00:00.000Z",
    estimatedMinutes: 120,
    syncStatus: "synced",
  },
  {
    id: "ot2",
    number: "OT-0002",
    title: "Averia por fuga en red secundaria",
    type: "breakdown",
    priority: "critical",
    status: "in_progress",
    billingStatus: "not_ready",
    clientId: "cliente2",
    clientName: "Cliente Industrial 2",
    equipmentId: "equipo3",
    equipmentLabel: "Deposito vertical",
    assignedTechnicianIds: ["tecnico2"],
    plannedStart: "2026-04-01T09:30:00.000Z",
    plannedEnd: "2026-04-01T12:00:00.000Z",
    estimatedMinutes: 150,
    syncStatus: "pending_sync",
  },
  {
    id: "ot3",
    number: "OT-0003",
    title: "Puesta en marcha tras cambio de repuesto",
    type: "commissioning",
    priority: "high",
    status: "planned",
    billingStatus: "not_ready",
    clientId: "cliente3",
    clientName: "Cliente Industrial 3",
    equipmentId: "equipo5",
    equipmentLabel: "Compresor respaldo",
    assignedTechnicianIds: ["tecnico3"],
    plannedStart: "2026-04-01T11:00:00.000Z",
    plannedEnd: "2026-04-01T13:00:00.000Z",
    estimatedMinutes: 120,
    syncStatus: "synced",
  },
  {
    id: "ot4",
    number: "OT-0004",
    title: "Visita tecnica y revision general",
    type: "technical_visit",
    priority: "normal",
    status: "planned",
    billingStatus: "not_ready",
    clientId: "cliente3",
    clientName: "Cliente Industrial 3",
    equipmentId: "equipo4",
    equipmentLabel: "Filtro principal",
    assignedTechnicianIds: ["tecnico4"],
    plannedStart: "2026-04-01T15:00:00.000Z",
    plannedEnd: "2026-04-01T16:30:00.000Z",
    estimatedMinutes: 90,
    syncStatus: "offline_only",
  },
];

export const workOrderDetails: WorkOrderDetail[] = workOrders.map((order) => ({
  ...order,
  description: `Detalle operativo de ${order.title}.`,
  checklist: [
    { id: `${order.id}-c1`, label: "Revisar estado general", done: true },
    { id: `${order.id}-c2`, label: "Comprobar consumibles", done: false },
    { id: `${order.id}-c3`, label: "Adjuntar observaciones finales", done: false },
  ],
  laborEntries: [
    { id: `${order.id}-l1`, technician: order.assignedTechnicianIds[0], minutes: 90, laborType: "onsite" },
  ],
  materials: [
    { id: `${order.id}-m1`, sku: "MAT-001", name: "Filtro separador", quantity: 1, unit: "ud" },
  ],
  logs: [
    {
      id: `${order.id}-log1`,
      at: "2026-04-01T08:10:00.000Z",
      author: order.assignedTechnicianIds[0],
      body: "Trabajo preparado para ejecucion.",
      source: "mobile",
    },
  ],
}));

export const workReports: WorkReport[] = [
  {
    id: "parte1",
    workOrderId: "ot1",
    workOrderNumber: "OT-0001",
    clientName: "Cliente Industrial 1",
    equipmentLabel: "Compresor principal",
    technicianId: "tecnico1",
    status: "draft",
    arrivalTime: "08:05",
    departureTime: "09:55",
    workDone: "Revision preventiva general y comprobacion visual.",
    pendingActions: "Pendiente validar vibracion en siguiente visita.",
    clientNameSigned: "",
    materials: [{ id: "pm1", sku: "MAT-001", name: "Filtro separador", quantity: 1, unit: "ud" }],
    attachments: [],
  },
  {
    id: "parte2",
    workOrderId: "ot2",
    workOrderNumber: "OT-0002",
    clientName: "Cliente Industrial 2",
    equipmentLabel: "Deposito vertical",
    technicianId: "tecnico2",
    status: "ready_for_review",
    arrivalTime: "09:40",
    departureTime: "11:50",
    workDone: "Localizada fuga y reparada conexion en derivacion secundaria.",
    pendingActions: "Revisar consumo en 7 dias.",
    clientNameSigned: "Responsable 2",
    materials: [{ id: "pm2", sku: "MAT-002", name: "Racor 1/2", quantity: 2, unit: "ud" }],
    attachments: [],
  },
];

export const plannerEvents: PlannerEvent[] = [
  {
    id: "ev1",
    workOrderId: "ot1",
    workOrderNumber: "OT-0001",
    startAt: "2026-04-01T08:00:00.000Z",
    endAt: "2026-04-01T10:00:00.000Z",
    title: "Mantenimiento preventivo trimestral",
    clientName: "Cliente Industrial 1",
    technicianId: "tecnico1",
    startHour: 8,
    startMinute: 0,
    durationMinutes: 120,
    status: "planned",
    priority: "normal",
    color: technicians[0].color,
  },
  {
    id: "ev2",
    workOrderId: "ot2",
    workOrderNumber: "OT-0002",
    startAt: "2026-04-01T09:30:00.000Z",
    endAt: "2026-04-01T12:00:00.000Z",
    title: "Averia por fuga en red secundaria",
    clientName: "Cliente Industrial 2",
    technicianId: "tecnico2",
    startHour: 9,
    startMinute: 30,
    durationMinutes: 150,
    status: "in_progress",
    priority: "critical",
    color: technicians[1].color,
  },
  {
    id: "ev3",
    workOrderId: "ot3",
    workOrderNumber: "OT-0003",
    startAt: "2026-04-01T11:00:00.000Z",
    endAt: "2026-04-01T13:00:00.000Z",
    title: "Puesta en marcha tras cambio de repuesto",
    clientName: "Cliente Industrial 3",
    technicianId: "tecnico3",
    startHour: 11,
    startMinute: 0,
    durationMinutes: 120,
    status: "planned",
    priority: "high",
    color: technicians[2].color,
  },
  {
    id: "ev4",
    workOrderId: "ot4",
    workOrderNumber: "OT-0004",
    startAt: "2026-04-01T15:00:00.000Z",
    endAt: "2026-04-01T16:30:00.000Z",
    title: "Visita tecnica y revision general",
    clientName: "Cliente Industrial 3",
    technicianId: "tecnico4",
    startHour: 15,
    startMinute: 0,
    durationMinutes: 90,
    status: "planned",
    priority: "normal",
    color: technicians[3].color,
  },
];

export const dashboardMetrics: DashboardMetric[] = [
  { id: "m1", label: "Ordenes abiertas", value: "12", helper: "Pendientes de ejecucion o cierre.", tone: "orange" },
  { id: "m2", label: "Tecnicos activos", value: "08", helper: "Todos disponibles para planificacion.", tone: "green" },
  { id: "m3", label: "Ordenes hoy", value: "15", helper: "Carga diaria visible por horas.", tone: "blue" },
  { id: "m4", label: "Ordenes pendientes", value: "04", helper: "Pendientes de oficina o firma.", tone: "red" },
];

export const dashboardAlerts: DashboardAlert[] = [
  {
    id: "a1",
    title: "tecnico2 ocupado hasta las 12:00",
    description: "Averia critica en Cliente Industrial 2 actualmente en curso.",
    severity: "critical",
  },
  {
    id: "a2",
    title: "Parte pendiente de revision",
    description: "OT-0002 tiene un parte listo para revision de oficina.",
    severity: "warning",
  },
];

export const technicianAgenda: TechnicianAgendaItem[] = workOrders.map((order) => ({
  id: order.id,
  number: order.number,
  title: order.title,
  client: order.clientName,
  equipmentLabel: order.equipmentLabel,
  windowLabel: `${order.plannedStart.slice(11, 16)} - ${order.plannedEnd.slice(11, 16)}`,
  status: order.status,
  syncStatus: order.syncStatus,
}));

export function getWorkOrderDetailById(id: string) {
  return workOrderDetails.find((workOrder) => workOrder.id === id) ?? null;
}
